version: '3.8'

services:
  mailcat:
    image: mengmengcode/mailcat:latest
    container_name: mailcat
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # API认证令牌 - 用于Cloudflare Worker调用API
      - MAILCAT_API_AUTH_TOKEN=your_auth_token
      # 管理员密码 - 用于Web管理界面登录
      - MAILCAT_ADMIN_PASSWORD=your_admin_password
      # 数据库路径 - 确保使用正确的路径
      - MAILCAT_DATABASE_PATH=/app/data/emails.db
      # 运行模式
      - GIN_MODE=release
      # 时区设置
      - TZ=Asia/Shanghai
    volumes:
      # 数据持久化 - SQLite数据库文件
      - mailcat_data:/app/data
      # 配置文件挂载（可选，如果需要自定义配置）
      # - ./config:/app/config:ro
    networks:
      - mailcat_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=mailcat"
      - "com.docker.compose.service=mailcat"

networks:
  mailcat_network:
    driver: bridge

volumes:
  mailcat_data:
    driver: local